#!/bin/sh

#compare with server
git log latest | grep commit | awk ' { print $2 }'>lll
(
date
echo "timing test"
echo "using"
java -version -server
) >time.server.out
for COM in `cat lll`
do
	echo $COM
	git checkout $COM latest/C64.jar
        java -server -jar latest/C64.jar -z -r "basic/ml3.basic" -x | egrep "JEBI|^Rate" >lll2
	cat lll2
	echo -n $COM " "
	echo -n `grep JEBI lll2` " "
	cat lll2 | awk '/Rate/ { rr=$3; if (rr>tt) {tt=rr;} if (NR>2) {ss=ss+rr;}} END { print "TOP = " tt " AVG = " ss/(NR-2.0) }'
done | tee time.server.out
